services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=profile'
      - 'MONGO_INITDB_ROOT_PASSWORD=test'
      - 'MONGO_INITDB_ROOT_USERNAME=test'
    ports:
      - '27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
